struct student *Delete(struct student *phead)// 删除学生信息
{
	struct student *p,*q;
	char a[10];
    int flag,line=33,row=7;
	while(1)
	{	
		system("cls");
		gotoxy(15,3);
		printf("===============================================");
		gotoxy(15,4);
		printf("|");
		gotoxy(61,4);
		printf("|");
		gotoxy(15,5);
		printf("|");
		gotoxy(61,5);
		printf("|");
		gotoxy(15,6);
		printf("|");
		gotoxy(61,6);
		printf("|");
		gotoxy(15,7);
		printf("|");
		gotoxy(61,7);
		printf("|");
		gotoxy(30,5);
		printf("请选择删除方式");
		gotoxy(35,7);
		printf("1.按学生ID");
		gotoxy(35,9);
		printf("2.按学生姓名");
		gotoxy(15,8);
		printf("|");
		gotoxy(61,8);
		printf("|");
		gotoxy(15,9);
		printf("|");
		gotoxy(61,9);
		printf("|");
		gotoxy(15,10);
		printf("|");
		gotoxy(61,10);
		printf("|");
		gotoxy(15,11);
		printf("|");
		gotoxy(61,11);
		printf("|");
		gotoxy(28,1);
		printf("★用方向键控制光标★");
		gotoxy(15,12);
		printf("===============================================");
		gotoxy(line,row);
		putch(16);
		flag=getch();
		if(flag==Up)
		{
			row=row-2;
			if(row==5)
				row=9;
		}
		else if(flag==Down)
		{
			row=row+2;
			if(row==11)
				row=7;
		}
		if(flag==13)
		{
			if(line==33&&row==7)
			{
				gotoxy(28,13);
				printf("请输入要删除的学生ID：\n");
				gotoxy(28,14);
	            scanf("%s",a);
				for(p=phead,q=phead->next;q!=NULL;p=p->next,q=q->next)
				{
					if(strcmp(a,q->ID)==0)
					{
						p->next=q->next;
						count--;
						gotoxy(28,15);
						printf("删除成功\n");
						break;
					}
				}
				if(q==NULL)
				{
					gotoxy(28,15);
					printf("对不起，没有这位同学的信息!\n");
				}
			 }
		     else if(line==33&&row==9)
			 {
				gotoxy(28,13);
				printf("请输入要删除的学生姓名：\n");
				gotoxy(28,14);
	            scanf("%s",a);
				for(p=phead,q=phead->next;q!=NULL;p=p->next,q=q->next)
				{
					if(strcmp(a,q->name)==0)
					{
						p->next=q->next;
						count--;
						gotoxy(28,15);
						printf("删除成功\n");
						break;
					}
				}
				if(q==NULL)
				{
					gotoxy(28,15);
					printf("对不起，没有这位同学的信息!\n");
				}
			 }
			 break;
		}
	}
	gotoxy(28,17);
	printf("按任意键返回主菜单\n");
	getch();
	return phead;
}
