void fail()// 计算学生成绩的及格率
{
	struct student *p;
	int flag,line=23,row=7,n=0;
	while(1)
	{	
		system("cls");
		gotoxy(15,3);
		printf("===============================================");
		gotoxy(15,4);
		printf("|");
		gotoxy(61,4);
		printf("|");
		gotoxy(15,5);
		printf("|");
		gotoxy(61,5);
		printf("|");
		gotoxy(15,6);
		printf("|");
		gotoxy(61,6);
		printf("|");
		gotoxy(15,7);
		printf("|");
		gotoxy(61,7);
		printf("|");
		gotoxy(30,5);
		printf("请选择统计科目");
		gotoxy(25,7);
		printf("1.平均分");
		gotoxy(25,9);
	    printf("3.数学");
		gotoxy(40,7);
        printf("2.语文");
		gotoxy(40,9);
		printf("4.英语");
		gotoxy(15,8);
		printf("|");
		gotoxy(61,8);
		printf("|");
		gotoxy(15,9);
		printf("|");
		gotoxy(61,9);
		printf("|");
		gotoxy(15,10);
		printf("|");
		gotoxy(61,10);
		printf("|");
		gotoxy(28,1);
		printf("★用方向键控制光标★");
		gotoxy(15,11);
		printf("===============================================");
		gotoxy(line,row);
		putch(16);
		flag=getch();
		if(flag==Up)
		{
			row=row-2;
			if(row==5)
				row=9;
		}
		else if(flag==Down)
		{
			row=row+2;
			if(row==11)
				row=7;
		}
		else if(flag==Left)
		{
			line=line-15;
			if(line==8)
				line=38;
		}
		else if(flag==Right)
		{
			line=line+15;
			if(line==53)
				line=23;
		}
		if(flag==13)
		{
			if(line==23&&row==7)
			{
				gotoxy(25,13);
				printf("********************************");
				for(p=phead->next;p!=NULL;p=p->next)
				{
					if(p->avg>=60)
						n++;
				}
				if(count!=0)
				{
					gotoxy(26,15);
					printf("统计人数为%d，及格率为%lf%%",count,((double)n/count)*100);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
				else
				{
					gotoxy(30,15);
					printf("统计人数为%d",count);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
			}
			else if(line==38&&row==7)
			{
				gotoxy(25,13);
				printf("********************************");
				for(p=phead->next;p!=NULL;p=p->next)
				{
					if(p->score[0]>=60)
						n++;
				}
				if(count!=0)
				{
					gotoxy(26,15);
					printf("统计人数为%d，及格率为%lf%%",count,((double)n/count)*100);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
				else
				{
					gotoxy(30,15);
					printf("统计人数为%d",count);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
			}
			else if(line==23&&row==9)
			{
				gotoxy(25,13);
				printf("********************************");
				for(p=phead->next;p!=NULL;p=p->next)
				{
					if(p->score[1]>=60)
						n++;
				}
				if(count!=0)
				{
					gotoxy(26,15);
					printf("统计人数为%d，及格率为%lf%%",count,((double)n/count)*100);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
				else
				{
					gotoxy(30,15);
					printf("统计人数为%d",count);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
			}
			else if(line==38&&row==9)
			{
				gotoxy(25,13);
				printf("********************************");
				for(p=phead->next;p!=NULL;p=p->next)
				{
					if(p->score[2]>=60)
						n++;
				}
			    if(count!=0)
				{
					gotoxy(26,15);
					printf("统计人数为%d，及格率为%lf%%",count,((double)n/count)*100);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
				else
				{
					gotoxy(30,15);
					printf("统计人数为%d",count);
					gotoxy(25,17);
					printf("********************************");
					break;
				}
			}
		}
	}
	gotoxy(35,19);
	printf("按任意键返回主菜单");
	getchar();
}