void find(struct student *phead)//  搜索
{
	struct student *p;
	char a[10],*q;
	int flag,line=33,row=7,x=0,i=0;
	while(1)
	{	
		system("cls");
		gotoxy(15,3);
		printf("===============================================");
		gotoxy(15,4);
		printf("|");
		gotoxy(61,4);
		printf("|");
		gotoxy(15,5);
		printf("|");
		gotoxy(61,5);
		printf("|");
		gotoxy(15,6);
		printf("|");
		gotoxy(61,6);
		printf("|");
		gotoxy(15,7);
		printf("|");
		gotoxy(61,7);
		printf("|");
		gotoxy(30,5);
		printf("请选择查找方式");
		gotoxy(35,7);
		printf("1.按学生ID");
		gotoxy(35,9);
		printf("2.按学生姓名");
		gotoxy(15,8);
		printf("|");
		gotoxy(61,8);
		printf("|");
		gotoxy(15,9);
		printf("|");
		gotoxy(61,9);
		printf("|");
		gotoxy(15,10);
		printf("|");
		gotoxy(61,10);
		printf("|");
		gotoxy(28,1);
		printf("★用方向键控制光标★");
		gotoxy(15,11);
		printf("===============================================");
		gotoxy(line,row);
		putch(16);
		flag=getch();
		if(flag==Up)
		{
			row=row-2;
			if(row==5)
				row=9;
		}
		else if(flag==Down)
		{
			row=row+2;
			if(row==11)
				row=7;
		}
		if(flag==13)
		{
			if(line==33&&row==7)
			{
				gotoxy(28,13);
				printf("请输入要查找的学生ID：\n");
				gotoxy(28,14);
	            scanf("%s",a);
			for(p=phead->next;p!=NULL;p=p->next)
				{
					q=strstr(p->ID,a); // 模糊查找
					if(q)
					{
						gotoxy(28,15+i*7);
						printf("******************************");
						gotoxy(28,16+i*7);
						printf("ID:%s",p->ID);
						gotoxy(28,17+i*7);
						printf("姓名:%s",p->name);
						gotoxy(28,18+i*7);
						printf("语文:%lf",p->score[0]);
						gotoxy(28,19+i*7);
						printf("数学:%lf",p->score[1]);
						gotoxy(28,20+i*7);
						printf("英语:%lf",p->score[2]);
						gotoxy(28,21+i*7);
					    printf("平均分:%lf",p->avg);
						x=1;
						i++;
					}
				}
				if(x==0)
				{
					gotoxy(28,16);
					printf("******************************");
					gotoxy(28,18);
					printf("对不起，没有这位同学的信息!\n");
					gotoxy(28,20);
					printf("******************************");
					gotoxy(28,22);
		            printf("按任意键返回主菜单\n");
		            getch();
				}
			}
			else if(line==33&&row==9)
			{
				gotoxy(28,13);
				printf("请输入要查找的学生姓名：\n");
				gotoxy(28,14);
	            scanf("%s",a);
				for(p=phead->next;p!=NULL;p=p->next)
				{
					q=strstr(p->name,a); // 模糊查找
					if(q)
					{
						gotoxy(28,15+i*7);
						printf("******************************");
						gotoxy(28,16+i*7);
						printf("ID:%s",p->ID);
						gotoxy(28,17+i*7);
						printf("姓名:%s",p->name);
						gotoxy(28,18+i*7);
						printf("语文:%lf",p->score[0]);
						gotoxy(28,19+i*7);
						printf("数学:%lf",p->score[1]);
						gotoxy(28,20+i*7);
						printf("英语:%lf",p->score[2]);
						gotoxy(28,21+i*7);
					    printf("平均分:%lf",p->avg);
						x=1;
						i++;
					}
				}
				if(x==0)
				{
					gotoxy(28,16);
					printf("******************************");
					gotoxy(28,18);
					printf("对不起，没有这位同学的信息!\n");
					gotoxy(28,20);
					printf("******************************");
					gotoxy(28,22);
		            printf("按任意键返回主菜单\n");
		            getch();
				}
			}
			break;
		}
	}
	if(x!=0)
	{
		gotoxy(28,22+(i-1)*7);
		printf("******************************");
		gotoxy(28,23+(i-1)*7);
		printf("按任意键返回主菜单\n");
		getch();
	}
}
