void print(struct student *phead)//  浏览 
{
	struct student *p ;
	int t=0;
	system("cls");
	if(count==0)
	{
		gotoxy(15,3);
		printf("对不起，当前还没有添加学生!\n");
	}
	else
	{
		gotoxy(15,3);
		printf("=================================================\n");
		gotoxy(15,4);
		printf("|");
		gotoxy(63,4);
		printf("|");
		for(p=phead->next;p!=NULL;p=p->next)
		{
			gotoxy(28,5+t*8);	
			printf("第%d位同学",t+1);
			gotoxy(15,5+t*8);
			printf("|");
			gotoxy(63,5+t*8);
			printf("|");
			gotoxy(25,6+t*8);
			printf("ID=%s",p->ID);
			gotoxy(15,6+t*8);
			printf("|");
			gotoxy(63,6+t*8);
			printf("|");
			gotoxy(25,7+t*8);
			printf("姓名=%s",p->name);
			gotoxy(15,7+t*8);
			printf("|");
			gotoxy(63,7+t*8);
			printf("|");
			gotoxy(25,8+t*8);
			printf("语文=%lf",p->score[0]);
			gotoxy(15,8+t*8);
			printf("|");
			gotoxy(63,8+t*8);
			printf("|");
			gotoxy(25,9+t*8);
			printf("数学=%lf",p->score[1]);
			gotoxy(15,9+t*8);
			printf("|");
			gotoxy(63,9+t*8);
			printf("|");
			gotoxy(25,10+t*8);
			printf("英语=%lf",p->score[2]);
			gotoxy(15,10+t*8);
			printf("|");
			gotoxy(63,10+t*8);
			printf("|");
			gotoxy(25,11+t*8);
			printf("平均分:%lf",p->avg);
			gotoxy(15,11+t*8);
			printf("|");
			gotoxy(63,11+t*8);
			printf("|");
			gotoxy(25,12+t*8);
			printf("******************************");
			t++;
		}
		gotoxy(15,13+(t-1)*8);
		printf("=================================================\n");
	}
	gotoxy(28,15+(t-1)*8);
	printf("按任意键返回主菜单\n");
	getch();
}