void welcome()//欢迎界面
{
	int i,j;
	char a[15];
	for(i=0;i<15;i++)
		a[i]='*';
	for(i=0;i<15;i++)
	{   
		system("cls");
		{
		   gotoxy(10,3);
	  	   printf("==============================================================");
		   gotoxy(10,4);
		   printf("|");
		   gotoxy(71,4);
		   printf("|");
		   gotoxy(10,5);
		   printf("|");
		   gotoxy(71,5);
		   printf("|");
		   gotoxy(10,6);
		   printf("|");
		   gotoxy(71,6);
		   printf("|");
		   gotoxy(35,6);
		   printf("欢  迎  来  到");
		   gotoxy(10,7);
		   printf("|");
		   gotoxy(71,7);
		   printf("|");
		   gotoxy(10,8);
		   printf("|");
		   gotoxy(71,8);
		   printf("|");
		   gotoxy(10,9);
		   printf("|");
		   gotoxy(71,9);
		   printf("|");
		   gotoxy(31,9);
		   printf("学  生  管  理  系  统");
		   gotoxy(10,10);
		   printf("|");
		   gotoxy(71,10);
		   printf("|");
		   gotoxy(10,11);
		   printf("|");
		   gotoxy(71,11);
		   printf("|");
		   gotoxy(20,12);
		   printf("----------------------------------------------");
		   gotoxy(66,14);
		   printf("%c",'\3');
		   gotoxy(22,14);
		   a[i]='\1';
	       for(j=0;j<=i;j++)
		      printf("%c  ",a[j]);
		   Sleep(100);
		   a[i]='*';
		   gotoxy(20,16);
		   printf("----------------------------------------------");
		   gotoxy(10,12);
		   printf("|");
		   gotoxy(71,12);
		   printf("|");
		    gotoxy(10,13);
		   printf("|");
		   gotoxy(71,13);
		   printf("|");
		    gotoxy(10,14);
		   printf("|");
		   gotoxy(71,14);
		   printf("|");
		    gotoxy(10,15);
		   printf("|");
		   gotoxy(71,15);
		   printf("|");
		    gotoxy(10,16);
		   printf("|");
		   gotoxy(71,16);
		   printf("|");
		    gotoxy(10,17);
		   printf("|");
		   gotoxy(71,17);
		   printf("|");
		    gotoxy(10,18);
		   printf("|");
		   gotoxy(71,18);
		   printf("|");
		    gotoxy(10,19);
		   printf("|");
		   gotoxy(71,19);
		   printf("|");
		    gotoxy(10,20);
		   printf("|");
		   gotoxy(71,20);
		   printf("|");
		   gotoxy(56,18);
		   printf("Made by lilu");
		   gotoxy(10,20);
		   printf("==============================================================");
		}
	}
	Sleep(2000);
}